[package]
name = "db_render"
version = "0.1.0"
edition = "2021"

[dependencies]
db_http_server = { version = "0.1.0", path = "../db_http_server" }
tokio = { version = "1.39.2", features = ["macros"] }