[package]
name = "db_shuttle"
version = "0.1.0"
edition = "2021"

[dependencies]
db_http_server = { version = "0.1.0", path = "../db_http_server" }
shuttle-runtime = "0.47.0"
shuttle-warp = "0.47.0"
tokio = "1.26.0"
warp = "0.3.3"
